CREATE DATABASE db_classificados 

USE db_classificados

CREATE TABLE Usuarios(
	Id_Usuario INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Senha VARCHAR(100) NOT NULL,
	Foto IMAGE NULL
) 

CREATE TABLE Anuncio (
	Id_Anuncio INT PRIMARY KEY IDENTITY NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	Preco REAL NOT NULL,
	Contato VARCHAR(50) NOT NULL,
	FK_Usuario INT NOT NULL,
	FOREIGN KEY (FK_Usuario) REFERENCES Usuarios (Id_Usuario)
)