CREATE DATABASE db_ecommerce

CREATE TABLE Usuarios(
	Id INT PRIMARY KEY NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Senha VARCHAR(50) NOT NULL,
	Endereco VARCHAR(50) NOT NULL
)

CREATE TABLE Produtos(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Tipo VARCHAR(50) NOT NULL,
	Preco FLOAT NOT NULL,
	Quantidade INT NOT NULL
	
)

CREATE TABLE Compras(
	FK_Clientes INT NOT NULL,
	FK_Produtos INT NOT NULL,
	FOREIGN KEY (FK_Clientes) REFERENCES Usuarios(Id),
	FOREIGN KEY (FK_Produtos) REFERENCES Produtos(Id),
)